language: php

php:
  - '7.0'
  - '7.1'

dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - chmod +x ./scripts/*
  - sudo sh ./scripts/travis_mysql_5.7.sh
  - mysql -e "create database IF NOT EXISTS settings;" -uroot

before_script:
  - composer self-update
  - composer install

script:
  - phpunit
